[package]
name = "backend"
version = "0.1.0"
authors = ["dtc103 <jan_kerner@gmx.de>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

